package channel

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"regexp"
	"strings"
	"sync"
	"time"

	common2 "github.com/QuantumNous/new-api/common"
	rootconstant "github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/logger"
	"github.com/QuantumNous/new-api/relay/common"
	"github.com/QuantumNous/new-api/relay/constant"
	"github.com/QuantumNous/new-api/relay/helper"
	"github.com/QuantumNous/new-api/relaykit/dto"
	"github.com/QuantumNous/new-api/relaykit/types"
	"github.com/QuantumNous/new-api/service"
	"github.com/QuantumNous/new-api/setting/model_setting"
	"github.com/QuantumNous/new-api/setting/operation_setting"

	"github.com/bytedance/gopkg/util/gopool"
	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/gorilla/websocket"
	"golang.org/x/net/http/httpguts"
)

const codexFallbackTurnIDContextKey = "codex_fallback_turn_id"

// ApplyUpstreamBodyMetadata restores metadata that net/http cannot infer from
// a ReplayableBody. Callers must pass the original body because NewRequest
// hides its dynamic type behind req.Body's io.ReadCloser wrapper.
func ApplyUpstreamBodyMetadata(req *http.Request, body io.Reader) {
	replayable, ok := body.(common2.ReplayableBody)
	if !ok {
		return
	}

	// BodyStorage structurally satisfies ReplayableBody, but it also exposes
	// io.Closer. If a caller passes the storage directly instead of using
	// NewReplayableBodyReader, hide Close before the transport takes ownership
	// of req.Body so the shared replay source remains available to GetBody.
	if _, rawStorage := body.(common2.BodyStorage); rawStorage {
		req.Body = io.NopCloser(body)
	}

	req.ContentLength = replayable.Size()
	if req.GetBody == nil {
		req.GetBody = replayable.NewReader
	}
}

func SetupApiRequestHeader(info *common.RelayInfo, c *gin.Context, req *http.Header) {
	if info.RelayMode == constant.RelayModeAudioTranscription || info.RelayMode == constant.RelayModeAudioTranslation {
		// multipart/form-data
	} else if info.RelayMode == constant.RelayModeRealtime {
		// websocket
	} else {
		req.Set("Content-Type", c.Request.Header.Get("Content-Type"))
		req.Set("Accept", c.Request.Header.Get("Accept"))
		if info.IsStream && c.Request.Header.Get("Accept") == "" {
			req.Set("Accept", "text/event-stream")
		}
	}
}

const clientHeaderPlaceholderPrefix = "{client_header:"

const (
	headerPassthroughAllKey        = "*"
	headerPassthroughRegexPrefix   = "re:"
	headerPassthroughRegexPrefixV2 = "regex:"
)

var passthroughSkipHeaderNamesLower = map[string]struct{}{
	// RFC 7230 hop-by-hop headers.
	"connection":          {},
	"keep-alive":          {},
	"proxy-authenticate":  {},
	"proxy-authorization": {},
	"te":                  {},
	"trailer":             {},
	"transfer-encoding":   {},
	"upgrade":             {},

	"cookie": {},

	// Additional headers that should not be forwarded by name-matching passthrough rules.
	"host":            {},
	"content-length":  {},
	"accept-encoding": {},

	// Do not passthrough credentials by wildcard/regex.
	"authorization":  {},
	"x-api-key":      {},
	"x-goog-api-key": {},

	// WebSocket handshake headers are generated by the client/dialer.
	"sec-websocket-key":        {},
	"sec-websocket-version":    {},
	"sec-websocket-extensions": {},
}

var headerPassthroughRegexCache sync.Map // map[string]*regexp.Regexp

func getHeaderPassthroughRegex(pattern string) (*regexp.Regexp, error) {
	pattern = strings.TrimSpace(pattern)
	if pattern == "" {
		return nil, errors.New("empty regex pattern")
	}
	if v, ok := headerPassthroughRegexCache.Load(pattern); ok {
		if re, ok := v.(*regexp.Regexp); ok {
			return re, nil
		}
		headerPassthroughRegexCache.Delete(pattern)
	}
	compiled, err := regexp.Compile(pattern)
	if err != nil {
		return nil, err
	}
	actual, _ := headerPassthroughRegexCache.LoadOrStore(pattern, compiled)
	if re, ok := actual.(*regexp.Regexp); ok {
		return re, nil
	}
	return compiled, nil
}

func IsHeaderPassthroughRuleKey(key string) bool {
	return isHeaderPassthroughRuleKey(key)
}
func isHeaderPassthroughRuleKey(key string) bool {
	key = strings.TrimSpace(key)
	if key == "" {
		return false
	}
	if key == headerPassthroughAllKey {
		return true
	}
	lower := strings.ToLower(key)
	return strings.HasPrefix(lower, headerPassthroughRegexPrefix) || strings.HasPrefix(lower, headerPassthroughRegexPrefixV2)
}

func shouldSkipPassthroughHeader(name string) bool {
	name = strings.TrimSpace(name)
	if name == "" {
		return true
	}
	lower := strings.ToLower(name)
	if _, ok := passthroughSkipHeaderNamesLower[lower]; ok {
		return true
	}
	return false
}

func removeNonForwardedRequestHeaders(header http.Header, rules []operation_setting.RequestHeaderRule) {
	for name := range header {
		if !operation_setting.ResolveRequestHeaderPolicy(name, rules).Forward {
			header.Del(name)
		}
	}
}

func isCodexUserAgent(userAgent string) bool {
	userAgent = strings.ToLower(strings.TrimSpace(userAgent))
	return strings.HasPrefix(userAgent, "codex desktop/") ||
		strings.HasPrefix(userAgent, "codex-tui/") ||
		strings.HasPrefix(userAgent, "codex_cli_rs/") ||
		strings.HasPrefix(userAgent, "codex-cli/")
}

func isCodexContextHeader(name string) bool {
	name = strings.ToLower(strings.TrimSpace(name))
	switch name {
	case "session-id", "session_id", "thread-id", "thread_id", "x-client-request-id",
		"x-oai-attestation", "x-openai-memgen-request", "x-openai-subagent",
		"x-responsesapi-include-timing-metrics":
		return true
	}
	return strings.HasPrefix(name, "x-codex-") ||
		strings.HasPrefix(name, "x-openai-internal-codex-")
}

func passCodexClientHeaders(c *gin.Context, upstream http.Header, info *common.RelayInfo) {
	if c == nil || c.Request == nil || upstream == nil || info == nil {
		return
	}
	format := info.GetFinalRequestRelayFormat()
	if format != types.RelayFormatOpenAI &&
		format != types.RelayFormatOpenAIResponses &&
		format != types.RelayFormatOpenAIResponsesCompaction &&
		format != types.RelayFormatOpenAIAlphaSearch {
		return
	}

	officialClient := isCodexUserAgent(c.Request.UserAgent())
	if !officialClient {
		settings := model_setting.GetCodexSettings()
		if info.ChannelMeta == nil ||
			(format != types.RelayFormatOpenAIResponses && format != types.RelayFormatOpenAIResponsesCompaction) ||
			!settings.RequestHeaderFallbackEnabled ||
			!model_setting.MatchesClientIdentityModel(settings.RequestHeaderModelPatterns, info.ChannelMeta.UpstreamModelName) {
			return
		}
	}

	for name, values := range c.Request.Header {
		if shouldSkipPassthroughHeader(name) || (!officialClient && !isCodexContextHeader(name)) {
			continue
		}
		upstream[name] = append([]string(nil), values...)
	}
}

func applyHeaderOverridePlaceholders(template string, c *gin.Context, apiKey string) (string, bool, error) {
	trimmed := strings.TrimSpace(template)
	if strings.HasPrefix(trimmed, clientHeaderPlaceholderPrefix) {
		afterPrefix := trimmed[len(clientHeaderPlaceholderPrefix):]
		end := strings.Index(afterPrefix, "}")
		if end < 0 || end != len(afterPrefix)-1 {
			return "", false, fmt.Errorf("client_header placeholder must be the full value: %q", template)
		}

		name := strings.TrimSpace(afterPrefix[:end])
		if name == "" {
			return "", false, fmt.Errorf("client_header placeholder name is empty: %q", template)
		}
		if c == nil || c.Request == nil {
			return "", false, fmt.Errorf("missing request context for client_header placeholder")
		}
		clientHeaderValue := c.Request.Header.Get(name)
		if strings.TrimSpace(clientHeaderValue) == "" {
			return "", false, nil
		}
		// Do not interpolate {api_key} inside client-supplied content.
		return clientHeaderValue, true, nil
	}

	if strings.Contains(template, "{api_key}") {
		template = strings.ReplaceAll(template, "{api_key}", apiKey)
	}
	if strings.TrimSpace(template) == "" {
		return "", false, nil
	}
	return template, true, nil
}

// processHeaderOverride applies channel header overrides, with placeholder substitution.
// Supported placeholders:
//   - {api_key}: resolved to the channel API key
//   - {client_header:<name>}: resolved to the incoming request header value
//
// Header passthrough rules (keys only; values are ignored):
//   - "*": passthrough all incoming headers by name (excluding unsafe headers)
//   - "re:<regex>" / "regex:<regex>": passthrough headers whose names match the regex (Go regexp)
//
// Passthrough rules are applied first, then normal overrides are applied, so explicit overrides win.
func processHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	headerOverride := make(map[string]string)
	if info == nil {
		return headerOverride, nil
	}

	headerOverrideSource := common.GetEffectiveHeaderOverride(info)

	passAll := false
	var passthroughRegex []*regexp.Regexp
	if !info.IsChannelTest {
		for k := range headerOverrideSource {
			key := strings.TrimSpace(strings.ToLower(k))
			if key == "" {
				continue
			}
			if key == headerPassthroughAllKey {
				passAll = true
				continue
			}

			var pattern string
			switch {
			case strings.HasPrefix(key, headerPassthroughRegexPrefix):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefix):])
			case strings.HasPrefix(key, headerPassthroughRegexPrefixV2):
				pattern = strings.TrimSpace(key[len(headerPassthroughRegexPrefixV2):])
			default:
				continue
			}

			if pattern == "" {
				return nil, types.NewError(fmt.Errorf("header passthrough regex pattern is empty: %q", k), types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			compiled, err := getHeaderPassthroughRegex(pattern)
			if err != nil {
				return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
			}
			passthroughRegex = append(passthroughRegex, compiled)
		}
	}

	if passAll || len(passthroughRegex) > 0 {
		if c == nil || c.Request == nil {
			return nil, types.NewError(fmt.Errorf("missing request context for header passthrough"), types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		for name := range c.Request.Header {
			if shouldSkipPassthroughHeader(name) {
				continue
			}
			if !passAll {
				matched := false
				for _, re := range passthroughRegex {
					if re.MatchString(name) {
						matched = true
						break
					}
				}
				if !matched {
					continue
				}
			}
			value := strings.TrimSpace(c.Request.Header.Get(name))
			if value == "" {
				continue
			}
			headerOverride[strings.ToLower(strings.TrimSpace(name))] = value
		}
	}

	for k, v := range headerOverrideSource {
		if isHeaderPassthroughRuleKey(k) {
			continue
		}
		key := strings.TrimSpace(strings.ToLower(k))
		if key == "" {
			continue
		}

		str, ok := v.(string)
		if !ok {
			return nil, types.NewError(nil, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if info.IsChannelTest && strings.HasPrefix(strings.TrimSpace(str), clientHeaderPlaceholderPrefix) {
			continue
		}

		value, include, err := applyHeaderOverridePlaceholders(str, c, info.ApiKey)
		if err != nil {
			return nil, types.NewError(err, types.ErrorCodeChannelHeaderOverrideInvalid)
		}
		if !include {
			continue
		}

		headerOverride[key] = value
	}
	return headerOverride, nil
}

func ResolveHeaderOverride(info *common.RelayInfo, c *gin.Context) (map[string]string, error) {
	return processHeaderOverride(info, c)
}

func applyHeaderOverrideToRequest(req *http.Request, headerOverride map[string]string) {
	if req == nil {
		return
	}
	for key, value := range headerOverride {
		req.Header.Set(key, value)
		// set Host in req
		if strings.EqualFold(key, "Host") {
			req.Host = value
		}
	}
}

func deleteManagedIdentityHeaders(header http.Header, exact []string, prefixes []string) {
	for name := range header {
		lowerName := strings.ToLower(name)
		for _, candidate := range exact {
			if strings.EqualFold(name, candidate) {
				header.Del(name)
				break
			}
		}
		for _, prefix := range prefixes {
			if strings.HasPrefix(lowerName, prefix) {
				header.Del(name)
				break
			}
		}
	}
}

func clearClaudeClientIdentity(header http.Header) {
	deleteManagedIdentityHeaders(
		header,
		[]string{"X-App", "X-Client-App"},
		[]string{"anthropic-", "x-anthropic-", "x-claude-", "x-stainless-"},
	)
}

func clearCodexClientIdentity(header http.Header) {
	deleteManagedIdentityHeaders(
		header,
		[]string{"Originator", "Version", "Session-Id", "Session_id", "Thread-Id", "Thread_id", "X-Client-Request-Id"},
		[]string{"x-codex-", "x-openai-internal-codex-", "x-oai-attestation"},
	)
}

func isCodexIdentityFormat(format types.RelayFormat) bool {
	return format == types.RelayFormatOpenAI ||
		format == types.RelayFormatOpenAIImage ||
		format == types.RelayFormatOpenAIAudio ||
		format == types.RelayFormatEmbedding ||
		format == types.RelayFormatOpenAIResponses ||
		format == types.RelayFormatOpenAIResponsesCompaction ||
		format == types.RelayFormatOpenAIAlphaSearch
}

// NormalizeClientIdentityHeaders applies the configured target client identity
// from the final request format and mapped upstream model for this attempt.
func NormalizeClientIdentityHeaders(c *gin.Context, req *http.Request, info *common.RelayInfo) {
	if req == nil || info == nil || info.ChannelMeta == nil {
		return
	}

	format := info.GetFinalRequestRelayFormat()
	upstreamModel := info.ChannelMeta.UpstreamModelName
	if isCodexIdentityFormat(format) {
		settings := model_setting.GetCodexSettings()
		if !settings.RequestHeaderFallbackEnabled ||
			!model_setting.MatchesClientIdentityModel(settings.RequestHeaderModelPatterns, upstreamModel) {
			return
		}
		if info.RelayFormat == types.RelayFormatClaude {
			clearClaudeClientIdentity(req.Header)
		}
		applyCodexClientIdentity(c, req, info, format, settings)
		return
	}

	if format != types.RelayFormatClaude {
		return
	}
	settings := model_setting.GetClaudeSettings()
	if !settings.RequestHeaderFallbackEnabled ||
		!model_setting.MatchesClientIdentityModel(settings.RequestHeaderModelPatterns, upstreamModel) {
		return
	}
	if isCodexIdentityFormat(info.RelayFormat) {
		clearCodexClientIdentity(req.Header)
	}
	if !strings.HasPrefix(strings.ToLower(strings.TrimSpace(req.Header.Get("User-Agent"))), "claude-cli/") {
		version := strings.TrimSpace(settings.RequestHeaderFallbackVersion)
		if model_setting.ValidateClientVersion(version) != nil {
			version = model_setting.DefaultClaudeCodeVersion
		}
		req.Header.Set("User-Agent", fmt.Sprintf("claude-cli/%s (external, cli)", version))
		req.Header.Set("X-App", "cli")
	} else if strings.TrimSpace(req.Header.Get("X-App")) == "" {
		req.Header.Set("X-App", "cli")
	}
}

func applyCodexClientIdentity(c *gin.Context, req *http.Request, info *common.RelayInfo, format types.RelayFormat, settings *model_setting.CodexSettings) {
	userAgentOnly := format == types.RelayFormatOpenAI ||
		format == types.RelayFormatOpenAIImage ||
		format == types.RelayFormatOpenAIAudio ||
		format == types.RelayFormatEmbedding
	responsesIdentity := format == types.RelayFormatOpenAIResponses ||
		format == types.RelayFormatOpenAIResponsesCompaction
	alphaSearchIdentity := format == types.RelayFormatOpenAIAlphaSearch

	clientVersion := strings.TrimSpace(settings.RequestHeaderFallbackVersion)
	if clientVersion == "" {
		clientVersion = model_setting.DefaultCodexClientVersion
	}
	componentOrDefault := func(value, fallback string) string {
		value = strings.TrimSpace(value)
		if model_setting.ValidateCodexUserAgentComponent(value) != nil {
			return fallback
		}
		return value
	}
	client := strings.TrimSpace(settings.RequestHeaderFallbackClient)
	if model_setting.ValidateCodexUserAgentClient(client) != nil {
		client = model_setting.DefaultCodexUserAgentClient
	}
	operatingSystem := componentOrDefault(settings.RequestHeaderFallbackOS, model_setting.DefaultCodexUserAgentOS)
	osVersion := componentOrDefault(settings.RequestHeaderFallbackOSVersion, model_setting.DefaultCodexUserAgentOSVersion)
	architecture := componentOrDefault(settings.RequestHeaderFallbackArchitecture, model_setting.DefaultCodexUserAgentArchitecture)
	terminal := componentOrDefault(settings.RequestHeaderFallbackTerminal, model_setting.DefaultCodexUserAgentTerminal)
	userAgent := fmt.Sprintf(
		"%s/%s (%s %s; %s) %s (%s; %s)",
		client,
		clientVersion,
		operatingSystem,
		osVersion,
		architecture,
		terminal,
		client,
		clientVersion,
	)

	incomingUserAgent := ""
	if c != nil && c.Request != nil {
		incomingUserAgent = strings.TrimSpace(c.Request.UserAgent())
	}
	if isCodexUserAgent(incomingUserAgent) {
		req.Header.Set("User-Agent", incomingUserAgent)
	} else if !isCodexUserAgent(req.Header.Get("User-Agent")) {
		req.Header.Set("User-Agent", userAgent)
	}
	if alphaSearchIdentity && strings.TrimSpace(req.Header.Get("Originator")) == "" {
		req.Header.Set("Originator", client)
	}
	// Only Responses formats carry Codex turn and session semantics.
	if userAgentOnly || alphaSearchIdentity || !responsesIdentity {
		return
	}

	firstHeader := func(names ...string) string {
		for _, name := range names {
			if value := strings.TrimSpace(req.Header.Get(name)); value != "" && httpguts.ValidHeaderFieldValue(value) {
				return value
			}
		}
		return ""
	}
	setIfMissingOrInvalid := func(name, value string) {
		current := strings.TrimSpace(req.Header.Get(name))
		if current == "" || !httpguts.ValidHeaderFieldValue(current) {
			req.Header.Set(name, value)
		}
	}

	rawTurnMetadata := strings.TrimSpace(req.Header.Get("X-Codex-Turn-Metadata"))
	turnMetadata := map[string]any{}
	turnMetadataValid := rawTurnMetadata != "" && common2.Unmarshal([]byte(rawTurnMetadata), &turnMetadata) == nil && turnMetadata != nil
	metadataString := func(name string) string {
		if !turnMetadataValid {
			return ""
		}
		value, ok := turnMetadata[name].(string)
		if !ok || !httpguts.ValidHeaderFieldValue(value) {
			return ""
		}
		return strings.TrimSpace(value)
	}

	// Reuse each supplied identity field before deriving or generating it so
	// fallback headers preserve the client's upstream session context.
	sessionID := firstHeader("Session-Id", "Session_id")
	if sessionID == "" {
		sessionID = metadataString("session_id")
	}
	if sessionID == "" {
		sessionID = firstHeader("Thread-Id", "Thread_id", "X-Client-Request-Id")
	}
	if sessionID == "" {
		var promptCacheKey string
		switch request := info.Request.(type) {
		case *dto.GeneralOpenAIRequest:
			promptCacheKey = strings.TrimSpace(request.PromptCacheKey)
		case *dto.OpenAIResponsesRequest:
			_ = common2.Unmarshal(request.PromptCacheKey, &promptCacheKey)
		case *dto.OpenAIResponsesCompactionRequest:
			_ = common2.Unmarshal(request.PromptCacheKey, &promptCacheKey)
		}
		if promptCacheKey != "" {
			if parsed, err := uuid.Parse(promptCacheKey); err == nil {
				sessionID = parsed.String()
			} else {
				sessionID = uuid.NewSHA1(uuid.NameSpaceOID, []byte(promptCacheKey)).String()
			}
		} else {
			requestID := ""
			if c != nil {
				requestID = strings.TrimSpace(c.GetString(common2.RequestIdKey))
			}
			if requestID != "" {
				// Retries share one inbound request ID, so deriving the fallback session
				// from it preserves upstream affinity without creating more state.
				sessionID = uuid.NewSHA1(uuid.NameSpaceOID, []byte(requestID)).String()
			} else {
				sessionID = newCodexUUIDV7()
			}
		}
	}

	threadID := firstHeader("Thread-Id", "Thread_id")
	if threadID == "" {
		threadID = metadataString("thread_id")
	}
	if threadID == "" {
		threadID = sessionID
	}
	installationID := firstHeader("X-Codex-Installation-Id")
	if installationID == "" {
		installationID = metadataString("installation_id")
	}
	if installationID == "" {
		channelIdentity := fmt.Sprintf("codex-installation:channel:%d", info.GetChannelID())
		installationID = uuid.NewSHA1(uuid.NameSpaceOID, []byte(common2.GenerateHMAC(channelIdentity))).String()
	}
	windowID := firstHeader("X-Codex-Window-Id")
	if windowID == "" {
		windowID = metadataString("window_id")
	}
	if windowID == "" {
		windowID = threadID + ":0"
	}
	turnID := metadataString("turn_id")
	if c != nil {
		if turnID == "" {
			turnID = strings.TrimSpace(c.GetString(codexFallbackTurnIDContextKey))
		}
	}
	if turnID == "" {
		turnID = newCodexUUIDV7()
		if c != nil {
			c.Set(codexFallbackTurnIDContextKey, turnID)
		}
	}
	requestKind := "turn"
	if format == types.RelayFormatOpenAIResponsesCompaction {
		requestKind = "compaction"
	}
	metadataChanged := !turnMetadataValid
	if !turnMetadataValid {
		turnMetadata = map[string]any{
			"thread_source": "user",
			"sandbox":       "none",
			"sandbox_mode":  "danger-full-access",
		}
	}
	setMetadataString := func(name, value string) {
		current, ok := turnMetadata[name].(string)
		if !ok || strings.TrimSpace(current) != value {
			turnMetadata[name] = value
			metadataChanged = true
		}
	}
	setMetadataString("installation_id", installationID)
	setMetadataString("session_id", sessionID)
	setMetadataString("thread_id", threadID)
	setMetadataString("turn_id", turnID)
	setMetadataString("window_id", windowID)
	setMetadataString("request_kind", requestKind)
	if metadataString("sandbox") == "" {
		turnMetadata["sandbox"] = "none"
		metadataChanged = true
	}
	if startedAt, ok := turnMetadata["turn_started_at_unix_ms"].(float64); !ok || startedAt <= 0 {
		turnMetadata["turn_started_at_unix_ms"] = time.Now().UnixMilli()
		metadataChanged = true
	}

	setIfMissingOrInvalid("Originator", client)
	setIfMissingOrInvalid("Session-Id", sessionID)
	setIfMissingOrInvalid("Thread-Id", threadID)
	setIfMissingOrInvalid("X-Client-Request-Id", threadID)
	setIfMissingOrInvalid("X-Codex-Window-Id", windowID)
	// X-Codex-Turn-State is server-issued sticky state and must never be forged.
	if metadataChanged {
		encodedMetadata, err := common2.Marshal(turnMetadata)
		if err != nil {
			logger.LogError(c, "marshal Codex turn metadata failed: "+err.Error())
			return
		}
		req.Header.Set("X-Codex-Turn-Metadata", string(encodedMetadata))
	}
}

func newCodexUUIDV7() string {
	id, err := uuid.NewV7()
	if err != nil {
		return uuid.NewString()
	}
	return id.String()
}

func DoApiRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	passCodexClientHeaders(c, req.Header, info)
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoFormRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	logger.LogDebug(c, "fullRequestURL: %s", common.SanitizeURLForLog(fullRequestURL))
	req, err := http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	// set form data
	req.Header.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	headers := req.Header
	err = a.SetupRequestHeader(c, &headers, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	passCodexClientHeaders(c, req.Header, info)
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	applyHeaderOverrideToRequest(req, headerOverride)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func DoWssRequest(a Adaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*websocket.Conn, error) {
	fullRequestURL, err := a.GetRequestURL(info)
	if err != nil {
		return nil, fmt.Errorf("get request url failed: %w", err)
	}
	targetHeader := http.Header{}
	err = a.SetupRequestHeader(c, &targetHeader, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	passCodexClientHeaders(c, targetHeader, info)
	// 在 SetupRequestHeader 之后应用 Header Override，确保用户设置优先级最高
	// 这样可以覆盖默认的 Authorization header 设置
	headerOverride, err := processHeaderOverride(info, c)
	if err != nil {
		return nil, err
	}
	for key, value := range headerOverride {
		targetHeader.Set(key, value)
	}
	targetHeader.Set("Content-Type", c.Request.Header.Get("Content-Type"))
	targetConn, _, err := websocket.DefaultDialer.DialContext(c.Request.Context(), fullRequestURL, targetHeader)
	if err != nil {
		return nil, fmt.Errorf("dial failed to %s: %w", common.SanitizeURLForLog(fullRequestURL), err)
	}
	// send request body
	//all, err := io.ReadAll(requestBody)
	//err = service.WssString(c, targetConn, string(all))
	return targetConn, nil
}

func startPingKeepAlive(c *gin.Context, pingInterval time.Duration) (context.CancelFunc, <-chan struct{}) {
	pingerCtx, stopPinger := context.WithCancel(context.Background())
	done := make(chan struct{})

	gopool.Go(func() {
		defer close(done)
		defer func() {
			// 增加panic恢复处理
			if r := recover(); r != nil {
				logger.LogDebug(c, "SSE ping goroutine panic recovered: %v", r)
			}
			logger.LogDebug(c, "SSE ping goroutine stopped")
		}()

		if pingInterval <= 0 {
			pingInterval = helper.DefaultPingInterval
		}

		ticker := time.NewTicker(pingInterval)
		// 确保在任何情况下都清理ticker
		defer func() {
			ticker.Stop()
			logger.LogDebug(c, "SSE ping ticker stopped")
		}()

		var pingMutex sync.Mutex
		logger.LogDebug(c, "SSE ping goroutine started")

		// 增加超时控制，防止goroutine长时间运行
		maxPingDuration := 120 * time.Minute // 最大ping持续时间
		pingTimeout := time.NewTimer(maxPingDuration)
		defer pingTimeout.Stop()

		for {
			select {
			// 发送 ping 数据
			case <-ticker.C:
				if err := sendPingData(c, &pingMutex); err != nil {
					logger.LogDebug(c, "SSE ping error, stopping goroutine: %s", err.Error())
					return
				}
			// 收到退出信号
			case <-pingerCtx.Done():
				return
			// request 结束
			case <-c.Request.Context().Done():
				return
			// 超时保护，防止goroutine无限运行
			case <-pingTimeout.C:
				logger.LogDebug(c, "SSE ping goroutine timeout, stopping")
				return
			}
		}
	})

	return stopPinger, done
}

func sendPingData(c *gin.Context, mutex *sync.Mutex) error {
	mutex.Lock()
	defer mutex.Unlock()

	// Bound the write so a slow client cannot block this goroutine forever;
	// doRequest's defer waits for the pinger to exit before returning.
	helper.ExtendWriteDeadline(c)
	err := helper.PingData(c)
	if err != nil {
		logger.LogError(c, "SSE ping error: "+err.Error())
		return err
	}

	logger.LogDebug(c, "SSE ping data sent")
	return nil
}

func DoRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	return doRequest(c, req, info)
}

// keepUpstreamRedirectResponse stops net/http from following redirects while
// returning the upstream 3xx response to the relay without an extra error.
func keepUpstreamRedirectResponse(_ *http.Request, _ []*http.Request) error {
	return http.ErrUseLastResponse
}

func doRequest(c *gin.Context, req *http.Request, info *common.RelayInfo) (*http.Response, error) {
	common2.SetContextKey(c, rootconstant.ContextKeyUpstreamRequestHeadersAudit, map[string]string(nil))
	if billingErr := service.PrepareTieredBillingForUpstreamRequest(c, info, req); billingErr != nil {
		return nil, billingErr
	}
	NormalizeClientIdentityHeaders(c, req, info)
	rules := operation_setting.GetRequestHeaderRules()
	removeNonForwardedRequestHeaders(req.Header, rules)
	if !operation_setting.ResolveRequestHeaderPolicy("Host", rules).Forward {
		req.Host = ""
	}
	client, err := service.GetHttpClientWithProxySettings(info.ChannelSetting.Proxy, info.ChannelSetting)
	if err != nil {
		return nil, fmt.Errorf("new proxy http client failed: %w", err)
	}
	// Clients are cached and shared across channels, so override redirect
	// behavior on a shallow copy instead of mutating the cached client. This
	// still reuses its transport and connection pools, including HTTP/2's
	// transparent stream retries.
	relayClient := *client
	relayClient.CheckRedirect = keepUpstreamRedirectResponse
	if common2.DebugEnabled && req != nil && req.URL != nil {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport select: host=%s protocol=%s shards=%d policy=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
		))
	}

	var stopPinger context.CancelFunc
	var pingerDone <-chan struct{}
	if info.IsStream {
		helper.SetEventStreamHeaders(c)
		// 处理流式请求的 ping 保活
		generalSettings := operation_setting.GetGeneralSetting()
		if generalSettings.PingIntervalEnabled && !info.DisablePing {
			pingInterval := time.Duration(generalSettings.PingIntervalSeconds) * time.Second
			stopPinger, pingerDone = startPingKeepAlive(c, pingInterval)
			// 使用defer确保在任何情况下都能停止ping goroutine
			defer func() {
				if stopPinger != nil {
					stopPinger()
					<-pingerDone
					logger.LogDebug(c, "SSE ping goroutine stopped by defer")
				}
			}()
		}
	}

	service.CaptureUpstreamRequestHeadersAudit(c, req.Header)
	resp, err := relayClient.Do(req)
	if err != nil {
		if errors.Is(err, context.Canceled) {
			return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithSkipRetry(), types.ErrOptionWithNoRecordErrorLog())
		}
		logger.LogError(c, "do request failed: "+err.Error())
		return nil, types.NewError(err, types.ErrorCodeDoRequestFailed, types.ErrOptionWithHideErrMsg("upstream error: do request failed"))
	}
	if resp == nil {
		return nil, errors.New("resp is nil")
	}
	if common2.DebugEnabled {
		policy := service.NormalizeHTTPTransportPolicy(info.ChannelSetting)
		logger.LogDebug(c, fmt.Sprintf(
			"http transport negotiated: host=%s protocol=%s shards=%d policy=%s negotiated=%s",
			req.URL.Host,
			policy.Protocol,
			policy.Shards,
			policy.String(),
			resp.Proto,
		))
	}

	if upID := resp.Header.Get(common2.RequestIdKey); upID != "" {
		c.Set(common2.UpstreamRequestIdKey, upID)
	}

	_ = req.Body.Close()
	_ = c.Request.Body.Close()
	return resp, nil
}

func DoTaskApiRequest(a TaskAdaptor, c *gin.Context, info *common.RelayInfo, requestBody io.Reader) (*http.Response, error) {
	fullRequestURL, err := a.BuildRequestURL(info)
	if err != nil {
		return nil, err
	}
	req, err := newTaskAPIRequest(c, fullRequestURL, requestBody)
	if err != nil {
		return nil, fmt.Errorf("new request failed: %w", err)
	}
	ApplyUpstreamBodyMetadata(req, requestBody)
	// Do NOT wrap requestBody in a GetBody closure here: returning the same
	// (already consumed) reader would make any transport-level retry silently
	// replay an empty body. http.NewRequest already derives a correct,
	// snapshot-based GetBody for *bytes.Reader/Buffer/strings.Reader bodies
	// (which most task adaptors pass in); ApplyUpstreamBodyMetadata wires the
	// same contract for bodies that explicitly implement ReplayableBody.
	// Otherwise GetBody stays nil so the transport fails the retry instead of
	// sending a corrupted request.

	err = a.BuildRequestHeader(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("setup request header failed: %w", err)
	}
	passCodexClientHeaders(c, req.Header, info)
	resp, err := doRequest(c, req, info)
	if err != nil {
		return nil, fmt.Errorf("do request failed: %w", err)
	}
	return resp, nil
}

func newTaskAPIRequest(c *gin.Context, fullRequestURL string, requestBody io.Reader) (*http.Request, error) {
	if c == nil || c.Request == nil {
		return nil, errors.New("task client request is missing")
	}
	return http.NewRequestWithContext(c.Request.Context(), c.Request.Method, fullRequestURL, requestBody)
}
