package controller

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/QuantumNous/new-api/common"
	"github.com/QuantumNous/new-api/constant"
	"github.com/QuantumNous/new-api/model"
)

// Legacy compact model aliases are recognized only so normalization can remove
// data written before compact became endpoint-only upstream behavior.
var channelNormalizationLegacyCompactModels = map[string]string{
	"gpt-5.5-openai-compact":       "gpt-5.5",
	"gpt-5.6-luna-openai-compact":  "gpt-5.6-luna",
	"gpt-5.6-sol-openai-compact":   "gpt-5.6-sol",
	"gpt-5.6-terra-openai-compact": "gpt-5.6-terra",
}

// The closed managed set prevents normalization from rewriting unrelated
// provider models merely because they share an OpenAI-compatible endpoint.
var channelNormalizationRegularModels = []string{
	"gpt-5.4",
	"gpt-5.4-mini",
	"gpt-5.5",
	"gpt-5.6-luna",
	"gpt-5.6-sol",
	"gpt-5.6-terra",
}

var channelNormalizationManagedModels = func() map[string]struct{} {
	models := map[string]struct{}{"codex-auto-review": {}}
	for _, modelName := range channelNormalizationRegularModels {
		models[modelName] = struct{}{}
	}
	for modelName := range channelNormalizationLegacyCompactModels {
		models[modelName] = struct{}{}
	}
	return models
}()

type channelNormalizationCandidate struct {
	Models          []string
	Mapping         map[string]string
	MappingWarnings map[string]string
}

// buildChannelNormalizationCandidate derives the safe target configuration from
// channel and upstreamModels. upstreamAccessible enables only conclusions that
// require a live model list; the returned candidate preserves user-owned names
// and mappings outside this feature's closed managed surface.
func buildChannelNormalizationCandidate(channel *model.Channel, upstreamModels []string, upstreamAccessible bool) (channelNormalizationCandidate, error) {
	oldModels := normalizeModelNames(channel.GetModels())
	oldMapping, err := parseStrictChannelMapping(channel)
	if err != nil {
		return channelNormalizationCandidate{}, err
	}

	retainedMapping := make(map[string]string, len(oldMapping))
	for alias, target := range oldMapping {
		// /v1/models cannot prove whether an alias is user-managed. Remove only
		// mappings generated by this feature whose behavior is now obsolete.
		if (alias == "gpt-5.4-mini" && target == "gpt-5.4") ||
			(alias == "codex-auto-review" && (target == "gpt-5.4" || target == "gpt-5.5")) ||
			isChannelNormalizationLegacyCompactMapping(alias, target) ||
			isChannelNormalizationThinkingMapping(alias, target) {
			continue
		}
		retainedMapping[alias] = target
	}

	upstreamSet := makeStringSet(upstreamModels)
	resolvedModels, resolvedMapping := resolveChannelNormalizationManagedModels(upstreamSet, retainedMapping)
	if upstreamAccessible {
		for _, upstreamModel := range upstreamModels {
			alias, target, ok := exposedClaudeModel(upstreamModel, upstreamSet)
			if !ok {
				continue
			}
			resolvedModels = append(resolvedModels, alias)
			if alias != target {
				if _, exists := resolvedMapping[alias]; !exists {
					resolvedMapping[alias] = target
				}
			}
		}
	}

	models := makeStringSet(resolvedModels)
	retainedAliases := makeStringSet(mapKeys(retainedMapping))
	for _, modelName := range oldModels {
		// Thinking variants are generated compatibility aliases, not stable public
		// model names, so normalization keeps only their base Claude model.
		if channelNormalizationThinkingBase(modelName) != "" {
			continue
		}
		_, managed := channelNormalizationManagedModels[modelName]
		_, retainedAlias := retainedAliases[modelName]
		// Unknown allowed models and explicit aliases remain user-owned; only the
		// closed managed/legacy surface is rewritten automatically.
		if retainedAlias || (!managed && isChannelNormalizationAllowedOpenAIModel(modelName)) {
			models[modelName] = struct{}{}
		}
	}
	for alias := range resolvedMapping {
		models[alias] = struct{}{}
	}
	mappingWarnings := map[string]string{}
	if upstreamAccessible {
		for alias, target := range retainedMapping {
			if resolvedMapping[alias] == target {
				if _, available := upstreamSet[target]; !available {
					mappingWarnings[alias] = target
				}
			}
		}
	}

	return channelNormalizationCandidate{
		Models:          sortedSetValues(models),
		Mapping:         resolvedMapping,
		MappingWarnings: mappingWarnings,
	}, nil
}

// resolveChannelNormalizationManagedModels resolves only the closed GPT/Codex
// surface against upstream while retaining explicit oldMapping entries. It
// returns exposed models and their required upstream targets.
func resolveChannelNormalizationManagedModels(upstream map[string]struct{}, oldMapping map[string]string) ([]string, map[string]string) {
	mapping := make(map[string]string, len(oldMapping)+2)
	for alias, target := range oldMapping {
		mapping[alias] = target
	}
	models := map[string]struct{}{}
	for _, modelName := range channelNormalizationRegularModels {
		if _, mapped := mapping[modelName]; mapped {
			models[modelName] = struct{}{}
			continue
		}
		if _, exists := upstream[modelName]; exists {
			models[modelName] = struct{}{}
		}
	}
	if _, provided := upstream["codex-auto-review"]; provided {
		models["codex-auto-review"] = struct{}{}
	}
	return sortedSetValues(models), mapping
}

// isChannelNormalizationTarget returns whether channel uses a supported type
// and contains at least one managed or legacy model/mapping this feature owns.
func isChannelNormalizationTarget(channel *model.Channel) bool {
	// These are the only channel types whose model surfaces follow the rules
	// defined here. Provider-specific channels must retain their own semantics.
	switch channel.Type {
	case constant.ChannelTypeOpenAI, constant.ChannelTypeAnthropic, constant.ChannelTypeAdvancedCustom:
	default:
		return false
	}
	for _, modelName := range channel.GetModels() {
		if isChannelNormalizationManagedOrLegacy(modelName) {
			return true
		}
	}
	mapping, err := parseStrictChannelMapping(channel)
	if err != nil {
		return true
	}
	for alias, target := range mapping {
		if isChannelNormalizationManagedOrLegacy(alias) || strings.HasPrefix(target, "claude-") || isChannelNormalizationLegacyCompactMapping(alias, target) {
			return true
		}
	}
	return false
}

func isChannelNormalizationManagedOrLegacy(modelName string) bool {
	if strings.HasPrefix(modelName, "claude-") {
		return true
	}
	if _, managed := channelNormalizationManagedModels[modelName]; managed {
		return true
	}
	return !isChannelNormalizationAllowedOpenAIModel(modelName)
}

// isChannelNormalizationAllowedOpenAIModel applies only this feature's GPT and
// image version floor; unrelated provider names remain user-controlled.
func isChannelNormalizationAllowedOpenAIModel(modelName string) bool {
	if modelName == "codex-auto-review" {
		return true
	}
	if strings.HasPrefix(modelName, "gpt-image-") {
		version := strings.TrimPrefix(modelName, "gpt-image-")
		parts := strings.FieldsFunc(version, func(r rune) bool { return r == '.' || r == '-' })
		if len(parts) == 0 {
			return false
		}
		majorText := parts[0]
		major, err := strconv.Atoi(majorText)
		return err == nil && major >= 2
	}
	if strings.HasPrefix(modelName, "codex-") {
		return false
	}
	if !strings.HasPrefix(modelName, "gpt-") {
		return true
	}
	version := strings.TrimPrefix(modelName, "gpt-")
	parts := strings.FieldsFunc(version, func(r rune) bool { return r == '.' || r == '-' })
	if len(parts) == 0 {
		return false
	}
	major, err := strconv.Atoi(parts[0])
	if err != nil {
		return false
	}
	minor := 0
	if len(parts) > 1 {
		minor, _ = strconv.Atoi(parts[1])
	}
	return major > 5 || major == 5 && minor >= 4
}

// exposedClaudeModel converts a supported upstream Claude ID into its public
// alias and mapping target. It returns ok=false for unsupported or generated
// thinking variants, except for the explicit legacy Haiku fallback.
func exposedClaudeModel(upstreamModel string, upstream map[string]struct{}) (string, string, bool) {
	if !strings.HasPrefix(upstreamModel, "claude-") || channelNormalizationThinkingBase(upstreamModel) != "" {
		return "", "", false
	}
	normalized := strings.ReplaceAll(upstreamModel, ".", "-")
	if !isSupportedChannelNormalizationClaude(normalized) {
		if normalized != "claude-haiku-4-5" {
			return "", "", false
		}
		// Upstreams may use dotted or hyphenated Claude versions. Normalize the
		// complete set before deciding whether this legacy fallback is needed.
		for candidate := range upstream {
			if strings.ReplaceAll(candidate, ".", "-") == "claude-haiku-4-5-20251001" {
				return "", "", false
			}
		}
		// When only the legacy 4.5 ID exists, expose the current dated public name
		// and retain the actual upstream ID as its mapping target.
		return "claude-haiku-4-5-20251001", upstreamModel, true
	}
	return normalized, upstreamModel, true
}

// isSupportedChannelNormalizationClaude compares known Claude families against
// their managed version floors. Unknown families return true so normalization
// does not delete provider models it cannot classify safely.
func isSupportedChannelNormalizationClaude(modelName string) bool {
	base := channelNormalizationThinkingBase(modelName)
	if base != "" {
		modelName = base
	}
	modelName = strings.ReplaceAll(modelName, ".", "-")
	parts := strings.Split(modelName, "-")
	if len(parts) < 4 || parts[0] != "claude" {
		return !strings.Contains(modelName, "sonnet") && !strings.Contains(modelName, "opus") && !strings.Contains(modelName, "haiku")
	}
	// These floors define the public Claude surface managed by this feature;
	// unknown families remain untouched rather than being guessed from a name.
	minimums := map[string][]int{
		"sonnet": {4, 6},
		"opus":   {4, 7},
		"haiku":  {4, 5, 20251001},
	}
	minimum, known := minimums[parts[1]]
	if !known {
		return true
	}
	version := make([]int, 0, len(parts)-2)
	for _, value := range parts[2:] {
		number, err := strconv.Atoi(value)
		if err != nil {
			return false
		}
		version = append(version, number)
	}
	for index := 0; index < max(len(version), len(minimum)); index++ {
		currentValue := 0
		minimumValue := 0
		if index < len(version) {
			currentValue = version[index]
		}
		if index < len(minimum) {
			minimumValue = minimum[index]
		}
		if currentValue != minimumValue {
			return currentValue > minimumValue
		}
	}
	return true
}

// parseStrictChannelMapping decodes and trims channel mappings. It returns an
// error instead of silently discarding malformed or empty entries because the
// normalizer may otherwise generate destructive diffs from incomplete state.
func parseStrictChannelMapping(channel *model.Channel) (map[string]string, error) {
	mapping := map[string]string{}
	raw := strings.TrimSpace(channel.GetModelMapping())
	if raw == "" || raw == "null" {
		return mapping, nil
	}
	if err := common.UnmarshalJsonStr(raw, &mapping); err != nil {
		return nil, fmt.Errorf("channel %d has invalid model_mapping: %w", channel.Id, err)
	}
	for alias, target := range mapping {
		normalizedAlias := strings.TrimSpace(alias)
		normalizedTarget := strings.TrimSpace(target)
		if normalizedAlias == "" || normalizedTarget == "" {
			return nil, fmt.Errorf("channel %d has an empty model_mapping entry", channel.Id)
		}
		if alias != normalizedAlias {
			delete(mapping, alias)
		}
		mapping[normalizedAlias] = normalizedTarget
	}
	return mapping, nil
}

func isChannelNormalizationLegacyCompactMapping(alias string, target string) bool {
	_, aliasCompact := channelNormalizationLegacyCompactModels[alias]
	_, targetCompact := channelNormalizationLegacyCompactModels[target]
	return aliasCompact || targetCompact
}

func isChannelNormalizationThinkingMapping(alias string, target string) bool {
	base := channelNormalizationThinkingBase(target)
	return base != "" && strings.ReplaceAll(base, ".", "-") == strings.ReplaceAll(alias, ".", "-")
}

func channelNormalizationThinkingBase(modelName string) string {
	if strings.HasPrefix(modelName, "claude-") && strings.HasSuffix(modelName, "-thinking") {
		return strings.TrimSuffix(modelName, "-thinking")
	}
	return ""
}

func makeStringSet(values []string) map[string]struct{} {
	result := make(map[string]struct{}, len(values))
	for _, value := range values {
		if value = strings.TrimSpace(value); value != "" {
			result[value] = struct{}{}
		}
	}
	return result
}

func sortedSetValues(values map[string]struct{}) []string {
	result := mapKeys(values)
	sort.Strings(result)
	return result
}

func mapKeys[V any](values map[string]V) []string {
	result := make([]string, 0, len(values))
	for key := range values {
		result = append(result, key)
	}
	return result
}
